version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=DEV
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:80"
  backend:
    environment:
      - NODE_ENV=DEV
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/dev.env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
