version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=DEV
    volumes:
      - ./frontend:/usr/src/app
    container_name: egads-site-frontend-dev
    ports:
      - "3000:80"
  backend:
    environment:
      - NODE_ENV=DEV
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/dev.env
    stdin_open: true
    container_name: egads-site-backend-dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
